#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    update-alternatives --remove x-www-browser /usr/bin/chromium-browser-stable
    update-alternatives --remove gnome-www-browser /usr/bin/chromium-browser-stable
    update-alternatives --remove chromium-browser /usr/bin/chromium-browser-stable
fi
